Repository CDCgov/PyRenew, pull requests merged in 2024-07, with the labels that each got.

#218 Create methods for simulating from prior and computing predictive distributions
  model/src/pyrenew/metaclass.py
  model/src/test/test_predictive.py
  model/src/test/test_random_key.py
Labels: development task

#251 Rename `SeedInfectionsExponential` For Clarity
  model/docs/example_with_datasets.qmd
  model/docs/extending_pyrenew.qmd
  model/src/pyrenew/latent/__init__.py
  model/src/pyrenew/latent/infection_seeding_method.py
  model/src/test/test_infection_seeding_method.py
  model/src/test/test_infection_seeding_process.py
Labels: clean up

#248 Changing `Model.sample` To `Model.model`
  model/src/pyrenew/metaclass.py
Labels: clean up

#191 Pyrenew tutorial review
  docs/source/tutorials/basic_renewal_model.rst
  docs/source/tutorials/hospital_admissions_model.rst
  docs/source/tutorials/index.rst
  model/docs/basic_renewal_model.qmd
  model/docs/getting_started.qmd
  model/docs/hospital_admissions_model.qmd
Labels: documentation

#257 sample multiple chain sequentially to avoid warning
  model/docs/basic_renewal_model.qmd
Labels: development task

#261 Renaming The Infections Seeding Initialization
  docs/source/msei_reference/latent.rst
  docs/source/tutorials/basic_renewal_model.qmd
  docs/source/tutorials/extending_pyrenew.qmd
  docs/source/tutorials/hospital_admissions_model.qmd
  docs/source/tutorials/pyrenew_demo.qmd
  model/src/pyrenew/latent/__init__.py
  model/src/pyrenew/latent/infection_initialization_method.py
  model/src/pyrenew/latent/infection_initialization_process.py
  model/src/pyrenew/latent/infections.py
  model/src/pyrenew/latent/infectionswithfeedback.py
  model/src/pyrenew/model/rtinfectionsrenewalmodel.py
  model/src/test/test_forecast.py
  model/src/test/test_infection_seeding_method.py
  model/src/test/test_infection_seeding_process.py
  model/src/test/test_infectionsrtfeedback.py
  model/src/test/test_latent_infections.py
  model/src/test/test_model_basic_renewal.py
  model/src/test/test_model_hospitalizations.py
  model/src/test/test_predictive.py
  model/src/test/test_random_key.py
Labels: clean up

#253 Add `__call__` As Alias For `RandomVariable` `sample` Method
  docs/source/tutorials/extending_pyrenew.qmd
  docs/source/tutorials/periodic_effects.qmd
  docs/source/tutorials/pyrenew_demo.qmd
  docs/source/tutorials/time.qmd
  model/src/pyrenew/arrayutils.py
  model/src/pyrenew/latent/hospitaladmissions.py
  model/src/pyrenew/latent/infection_initialization_method.py
  model/src/pyrenew/latent/infection_initialization_process.py
  model/src/pyrenew/latent/infections.py
  model/src/pyrenew/latent/infectionswithfeedback.py
  model/src/pyrenew/metaclass.py
  model/src/pyrenew/model/admissionsmodel.py
  model/src/pyrenew/model/rtinfectionsrenewalmodel.py
  model/src/pyrenew/process/firstdifferencear.py
  model/src/pyrenew/process/periodiceffect.py
  model/src/pyrenew/process/rtperiodicdiff.py
  model/src/pyrenew/process/rtrandomwalk.py
  model/src/pyrenew/regression.py
  model/src/test/test_ar_process.py
  model/src/test/test_deterministic.py
  model/src/test/test_first_difference_ar.py
  model/src/test/test_infection_seeding_method.py
  model/src/test/test_infection_seeding_process.py
  model/src/test/test_infectionsrtfeedback.py
  model/src/test/test_latent_admissions.py
  model/src/test/test_latent_infections.py
  model/src/test/test_observation_negativebinom.py
  model/src/test/test_observation_poisson.py
  model/src/test/test_periodiceffect.py
  model/src/test/test_random_walk.py
  model/src/test/test_regression.py
  model/src/test/test_rtperiodicdiff.py
Labels: clean up

#303 Additional `seed` To `init` Changes
  docs/source/tutorials/time.qmd
  model/src/pyrenew/latent/infection_initialization_method.py
  model/src/pyrenew/latent/infection_initialization_process.py
  model/src/test/test_infection_seeding_method.py
Labels: clean up

#305 Change Naming Of `n_timepoints_to_simulate`
  docs/source/tutorials/basic_renewal_model.qmd
  docs/source/tutorials/extending_pyrenew.qmd
  docs/source/tutorials/hospital_admissions_model.qmd
  model/src/pyrenew/model/admissionsmodel.py
  model/src/pyrenew/model/rtinfectionsrenewalmodel.py
  model/src/test/test_forecast.py
  model/src/test/test_model_basic_renewal.py
  model/src/test/test_model_hosp_admissions.py
  model/src/test/test_predictive.py
  model/src/test/test_random_key.py
Labels: clean up

#317 Maintain Consistent `rng_key` Valuing
  model/src/test/test_model_hosp_admissions.py
Labels: clean up

#316 Change Certain `numpyro`s To `npro`
  docs/source/tutorials/extending_pyrenew.qmd
  docs/source/tutorials/periodic_effects.qmd
  model/src/pyrenew/deterministic/deterministic.py
  model/src/pyrenew/latent/hospitaladmissions.py
  model/src/pyrenew/latent/infection_initialization_process.py
  model/src/pyrenew/latent/infectionswithfeedback.py
  model/src/pyrenew/metaclass.py
  model/src/test/test_forecast.py
  model/src/test/test_infection_seeding_process.py
  model/src/test/test_infectionsrtfeedback.py
  model/src/test/test_latent_admissions.py
  model/src/test/test_latent_infections.py
  model/src/test/test_model_basic_renewal.py
  model/src/test/test_observation_negativebinom.py
  model/src/test/test_observation_poisson.py
  model/src/test/test_periodiceffect.py
  model/src/test/test_rtperiodicdiff.py
Labels: clean up

#292 Bump polars version and merge all `pyproject.toml`s to single top level `pyproject.toml`
  .github/workflows/test_model.yml
  .github/workflows/test_pipeline.yml
  .github/workflows/website.yaml
  docs/pyproject.toml
  model/pyproject.toml
  pyproject.toml
Labels: developer

#321 Fixing Remaining Instances Of `np.random.seed()` For `rng_seed`
  docs/source/tutorials/extending_pyrenew.qmd
  model/src/test/test_forecast.py
  model/src/test/test_latent_admissions.py
  model/src/test/test_latent_infections.py
  model/src/test/test_model_basic_renewal.py
  model/src/test/test_observation_negativebinom.py
  model/src/test/test_observation_poisson.py
  model/src/test/test_periodiceffect.py
  model/src/test/test_random_key.py
  model/src/test/test_rtperiodicdiff.py
Labels: clean up

#327 Solve `test_rtperiodicdiff.py` Test Failures
  model/src/test/test_rtperiodicdiff.py
Labels: bug

#324 Change Order Of The `name` Argument To Match Numpyro
  docs/source/tutorials/basic_renewal_model.qmd
  docs/source/tutorials/extending_pyrenew.qmd
  docs/source/tutorials/hospital_admissions_model.qmd
  docs/source/tutorials/periodic_effects.qmd
  model/src/pyrenew/deterministic/deterministic.py
  model/src/pyrenew/deterministic/deterministicpmf.py
  model/src/pyrenew/latent/hospitaladmissions.py
  model/src/pyrenew/metaclass.py
  model/src/pyrenew/process/firstdifferencear.py
  model/src/test/test_deterministic.py
  model/src/test/test_forecast.py
  model/src/test/test_infection_seeding_method.py
  model/src/test/test_infection_seeding_process.py
  model/src/test/test_infectionsrtfeedback.py
  model/src/test/test_latent_admissions.py
  model/src/test/test_latent_infections.py
  model/src/test/test_model_basic_renewal.py
  model/src/test/test_model_hosp_admissions.py
  model/src/test/test_observation_negativebinom.py
  model/src/test/test_periodiceffect.py
  model/src/test/test_predictive.py
  model/src/test/test_random_key.py
  model/src/test/test_random_walk.py
  model/src/test/test_rtperiodicdiff.py
  model/src/test/test_transformed_rv_class.py
Labels: clean up, pyrenew

#331 Rename Deterministic `vars` Attribute To `value`
  docs/source/tutorials/basic_renewal_model.qmd
  docs/source/tutorials/extending_pyrenew.qmd
  docs/source/tutorials/hospital_admissions_model.qmd
  docs/source/tutorials/periodic_effects.qmd
  model/src/pyrenew/deterministic/deterministic.py
  model/src/pyrenew/deterministic/deterministicpmf.py
  model/src/pyrenew/latent/hospitaladmissions.py
  model/src/test/test_deterministic.py
  model/src/test/test_forecast.py
  model/src/test/test_infection_seeding_method.py
  model/src/test/test_infection_seeding_process.py
  model/src/test/test_infectionsrtfeedback.py
  model/src/test/test_latent_admissions.py
  model/src/test/test_model_basic_renewal.py
  model/src/test/test_model_hosp_admissions.py
  model/src/test/test_observation_negativebinom.py
  model/src/test/test_periodiceffect.py
  model/src/test/test_predictive.py
  model/src/test/test_random_key.py
  model/src/test/test_random_walk.py
  model/src/test/test_rtperiodicdiff.py
Labels: clean up
