Repository CDCgov/PyRenew, pull requests merged in 2024-06, with the labels that each got.

#192 Pseudo-Random Number Generation For None Input For JAX PRNGKey In Metaclass
  model/src/pyrenew/metaclass.py
  model/src/test/test_model_basic_renewal.py
  model/src/test/test_model_hospitalizations.py
  model/src/test/test_random_key.py
Labels: enhancement

#197 Adding Repository Structure And Resources Sections To The README
  README.md
Labels: documentation

#205 Renaming infections_mean_varname to infections_varname
  model/docs/example_with_datasets.qmd
  model/docs/extending_pyrenew.qmd
  model/docs/getting_started.qmd
  model/src/pyrenew/latent/infections.py
  model/src/pyrenew/latent/infectionswithfeedback.py
  model/src/pyrenew/model/rtinfectionsrenewalmodel.py
  model/src/test/test_model_basic_renewal.py
Labels: clean up
